on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      APP_ID: com.example.flutter_chat_app
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: flutter-fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter-fvm-config-action.outputs.FLUTTER_VERSION }}
          cache: true
      - run: flutter pub get
      - run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/src/google-services.json
          echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIT }}' > ios/Runner/GoogleService-Info.plist
          echo '${{ secrets.FIREBASE_OPTIONS_DART }}' > lib/firebase_options.dart
      - run: |
          cat android/app/src/google-services.json
          cat ios/Runner/GoogleService-Info.plist
          cat lib/firebase_options.dart
      - run: flutter analyze